### PR TITLE
Bugfix/46 quality profiles disappear on first installation

### LINKED ISSUE #46: Quality profiles disappear on new installation
When SonarQube is installed and **before** its first start quality profiles are put to their regarding volume `qualityprofiles` these quality profiles are not properly imported after the initial start.

Seemingly any plugins to be installed play into this situation.

**Steps to reproduce:**

1. install SonarQube
1. copy any custom quality profile into /var/lib/ces/sonar/volumes/qualityprofiles
    - [java-sonar-borito-12710.xml.txt](https://github.com/cloudogu/sonar/files/5169285/java-sonar-borito-12710.xml.txt)
1. set plugins to be installed
   - `etcdctl set /config/sonar/sonar.plugins.default pmd,findbugs,xml,php,python,typescript,scmsvn,scmgit,javascript,flex,java,csharp,checkstyle,web,communityBranchPlugin,authgithub,authsaml,cssfamily,go,web,jacoco,kotlin,ruby,sonarscala,scmgit,scmsvn,vbnet`
   - plugins are going to be fetched from the internet
1. start SonarQube
1. once up, open SonarQube go to page "Quality Profiles"
1. open imported profile and behold! It is empty!

This defect was observed in SonarQube dogu versions 
- 7.9.1-4
- 7.9.3-1
- 7.9.3-2 (current)

### PR DESCRIPTION
**Pull request by ppxl**
This PR resolves #46 by changing the order of plugin installation, SonarQube-Restart and quality profile import.

Since there is a non-trivial dependency from quality profiles to installed plugins this PR solves the matter by adding another SonarQube restart. This restart takes only place when there are actually quality profiles to be imported. Otherwise the restart is skipped in order to shave off unnecessary downtime.

### CODE REVIEW

File: resources/startup.sh [hunk 1]
```diff
@@ -34,33 +46,60 @@ TEMPORARY_ADMIN_GROUP=$(doguctl random)
...
-    done;
+
+  local resultCode
+  if [[ "$(ls -A ${QUALITY_PROFILE_DIR})" ]]; then
+    echo "Quality profiles are present..."
+    resultCode=0
   else
-    echo "No quality profiles to import"
-  fi;
+    echo "There are no quality profiles..."
```
Comment (robertauer) [inline resources/startup.sh:57]: This statement does only apply to the quality profile directory and not to SonarQube in general, so it may be misleading in the log.
```suggestion
    echo "There are no quality profiles for import present..."
```

File: resources/startup.sh [hunk 2]
```diff
@@ -34,33 +46,60 @@ TEMPORARY_ADMIN_GROUP=$(doguctl random)
...
-        echo "Removed $file file"
-      else
-        echo "Import of quality profile $file has not been successful"
-        echo "${RESPONSE_IMPORT}"
-      fi;
-    done;
+
+  local resultCode
+  if [[ "$(ls -A ${QUALITY_PROFILE_DIR})" ]]; then
+    echo "Quality profiles are present..."
```
Comment (robertauer) [inline resources/startup.sh:54]: This statement does only apply to the quality profile directory and not to SonarQube in general, so it may be misleading in the log.
```suggestion
    echo "Quality profiles are present for import..."
```

File: resources/startup.sh [hunk 3]
```diff
@@ -34,33 +46,60 @@ TEMPORARY_ADMIN_GROUP=$(doguctl random)
 TEMPORARY_ADMIN_USER=$(doguctl random)
 TEMPORARY_ADMIN_PASSWORD=$(doguctl random)
 
-function import_quality_profiles_if_present {
-  AUTH_USER=$1
-  AUTH_PASSWORD=$2
+function areQualityProfilesPresent() {
```
Comment (robertauer) [inline resources/startup.sh:49]: This function name does only apply to the quality profile directory and not to SonarQube in general.
```suggestion
function areQualityProfilesPresentForImport() {
```

File: resources/startup.sh [hunk 4]
```diff
@@ -410,6 +467,20 @@ fi
 echo "Removing temporary admin..."
 remove_temporary_admin_user_and_group
 
+# Please note!
```
Comment (robertauer) [inline resources/startup.sh:470]: This line is irrelevant, as you could write that on pretty much every comment line

File: resources/startup.sh [hunk 5]
```diff
@@ -34,33 +46,60 @@ TEMPORARY_ADMIN_GROUP=$(doguctl random)
...
+
+      echo "Import of quality profile for ${file} returned with: ${importSuccesses} rules okay, ${importFailures} rules failed."
+
+      if [[ "${importSuccesses}" == "0" ]]; then
+        echo "WARNING: No quality profiles could be imported from file ${file}. Import returned: '${importResponse}'"
+      fi
+
+      if [[ "${importFailures}" != "0" ]]; then
+        echo "ERROR: There were quality profiles import failures from file ${file}. Import returned: '${importResponse}'"
+        # do not remove file so the customer has the chance to  the file content
```
Comment (robertauer) [inline resources/startup.sh:90]:
```suggestion
        # do not remove file so the user has the chance to examine the file content
```

File: resources/startup.sh (hunk 1 above)
Comment (ppxl) [reply resources/startup.sh:57]: Ahh, good point! I'll take it into account

File: resources/startup.sh (hunk 2 above)
Comment (ppxl) [reply resources/startup.sh:54]: Hmmm, this is a code duplication with that from above (line 57). But point is taken

File: resources/startup.sh (hunk 3 above)
Comment (ppxl) [reply resources/startup.sh:49]: point taken

File: resources/startup.sh (hunk 4 above)
Comment (ppxl) [reply resources/startup.sh:470]: Then how would declare such an order problem? It was already unclear in the beginning that's why I ran into import problems.

Comment (ppxl) [reply resources/startup.sh:470]: On 2nd reading I understand that you mean not the whole comment block but this specific line and I do agree.

Comment (robertauer) [reply resources/startup.sh]: The declaration that is coming afterwards is totally fine, I just think it does not need a special headline. Otherwise everyone would declare their problem as notably in the future and the code gets bloated with "THIS IS IMPORTANT!" notes.
