### PR TITLE
Bugfix/63 fix cas identity provider by db migration

### LINKED ISSUE #63: CAS authentication fails after SonarQube migration 7 -> 8
**concerned versions:**
SonarQube v7.9.4-4 and v8.9.0-2

SonarQube produces an authentication error with CAS accounts that previously were logged-in into SonarQube at one point in time.

The error log reads:

```
Jul 16 13:42:24 ces-server docker/sonar[2059]: 2021.07.16 13:42:24 ERROR web[AXqvFWcTDEzaihGFAAAK][o.s.p.c.CasIdentityProvider] authentication or logout failed
Jul 16 13:42:24 ces-server docker/sonar[2059]: org.jasig.cas.client.validation.TicketValidationException:
Jul 16 13:42:24 ces-server docker/sonar[2059]: #011#011Ticket 'ST-10-CdaHauvWvcnTmWbeCcrO-cas.ces.local' not recognized
```

This issue was caused by the recent release of [Sonar-CAS-Plugin](https://github.com/cloudogu/sonar-cas-plugin/releases/tag/v4.0.0) in conjunction with SQ 8. The change of the Identity Provider key `cas` to `sonarqube` plays most likely a major role in this situation.

### PR DESCRIPTION
**Pull request by ppxl**
resolve #63 by db migration. Since there may already exist SQ instances with this problem, the DB migration is not excluded to a major upgrade. Instead all upgrades within the SQ version n8 range will apply. This migration is rather harmless because a very specific and small set of values will be changed.

Also this PR adds several shell tests and changes that enable tests in the first place.

### CODE REVIEW

File: resources/upgrade-notification.sh [hunk 1]
```diff
@@ -1,22 +1,50 @@
...
+    echo "Please follow the upgrade path of one major version to the next one instead."
+    exit 1
+  fi
+
+  if [[ ${FROM_VERSION} == "7.9."* ]] && [[ ${TO_VERSION} == "8.9."* ]]; then
+    echo "You are upgrading your SonarQube instance from 7.9.x LTS to 8.9.x LTS. Please consider backing up your SonarQube database."
+    echo "Upgrade problems are rare, but you may want backup in case anything goes wrong."
+    echo "Some plugins will be uninstalled because SonarQube 8.9 includes the plugin functionality into its core."
+    echo "Please check the SonarQube plugin compatibility in the release notes. Concerned plugins will move to"
+    echo "$(extensions/deprecated-plugins/) in case you need them."
```
Comment (robertauer) [inline resources/upgrade-notification.sh:40]: This has to be escaped or something, because it leads to a faulty output:
```
Please check the SonarQube plugin compatibility in the release notes. Concerned plugins will move to
/upgrade-notification.sh: line 40: extensions/deprecated-plugins/: No such file or directory
 in case you need them.
```

**Review by robertauer — CHANGES_REQUESTED** [review]

File: resources/post-upgrade.sh [hunk 2]
```diff
@@ -44,82 +36,103 @@ function reinstall_plugins() {
...
-fi
+  if [[ "${TO_MAJOR_VERSION}" -eq 8 ]]; then
+    migrate_cas_identity_provider_in_db
+  fi
 
-doguctl config post_upgrade_running false
+  doguctl config post_upgrade_running false
+}
+
+# make the script only run when executed, not when sourced from bats tests)
```
Comment (robertauer) [inline resources/post-upgrade.sh:135]:
```suggestion
# make the script only run when executed, not when sourced from bats tests
```

**Review by robertauer — CHANGES_REQUESTED** [review]

**Review by robertauer — APPROVED** [review]
