### PR TITLE
Fix mail config

### LINKED ISSUE #170: Fix mail configuration
In v25 the configuration has to be set in internal_properties table

### PR DESCRIPTION
**Pull request by nhinze23**
Resolves #170

### CODE REVIEW

File: resources/startup.sh [hunk 1]
```diff
@@ -561,6 +558,30 @@ function setDoguLogLevel() {
...
+  # Unfortunately, there is no REST API to set internal properties, so we have to use plain SQL statements.
+  # This command "upserts" the mail configuration.
+  echo "Setting email configuration..."
+  execute_sql_statement_on_database "
+INSERT INTO internal_properties (kee, is_empty, text_value, created_at)
+VALUES
+  ('email.smtp_host.secured', 'f', 'postfix', (extract(epoch from now()) * 1000)::bigint),
+  ('email.smtp_port.secured', 'f', '25', (extract(epoch from now()) * 1000)::bigint),
+  ('email.smtp_username.secured', 't', '', (extract(epoch from now()) * 1000)::bigint),
+  ('email.smtp_password.secured', 't', '', (extract(epoch from now()) * 1000)::bigint),
```
Comment (meiserloh) [inline resources/startup.sh:573]: not that it would've worked before, but this doesn't work when actually username and pw are set or is this connection always unauthorized?

Comment (nhinze23) [reply resources/startup.sh:573]: Setting credentials does not make sense because the postfix dogu does not offer service accounts.

Comment (nhinze23) [reply resources/startup.sh:573]: For now :stuck_out_tongue:
